# Generated by Django 5.0.9 on 2024-11-23 16:09

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок, отображаемый в браузере и поисковых системах",
                        max_length=160,
                        verbose_name="Заголовок страницы",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный идентификатор для URL-адреса страницы",
                        max_length=160,
                        unique=True,
                        verbose_name="URL-адрес (Slug)",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Тип или категория содержимого страницы (например, 'Статья' или 'Новость')",
                        max_length=160,
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "og_image",
                    models.URLField(
                        help_text="Полный URL изображения, отображаемого при публикации ссылки в соцсетях",
                        max_length=250,
                        verbose_name="URL изображения для Open Graph",
                    ),
                ),
                (
                    "og_image_alt",
                    models.CharField(
                        blank=True,
                        help_text="Альтернативный текст для изображения (если требуется)",
                        max_length=250,
                        verbose_name="Описание изображения (alt-текст)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Краткое описание для поисковых систем (не более 160 символов)",
                        max_length=160,
                        verbose_name="Описание страницы (meta description)",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        choices=[
                            ("index, follow", "Индексировать и следовать"),
                            ("noindex, follow", "Не индексировать, но следовать"),
                            ("index, nofollow", "Индексировать, но не следовать"),
                            ("noindex, nofollow", "Не индексировать и не следовать"),
                        ],
                        default="index, follow",
                        help_text="Укажите, как поисковые системы должны обрабатывать страницу",
                        max_length=500,
                        verbose_name="Инструкции для поисковых систем (meta robots)",
                    ),
                ),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Текст публикации"
                    ),
                ),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-publish"],
                "indexes": [
                    models.Index(
                        fields=["-publish"], name="blog_post_publish_bb7600_idx"
                    ),
                    models.Index(fields=["slug"], name="blog_post_slug_cdb902_idx"),
                ],
            },
        ),
    ]
